name: Lint Frontend

on:
  push:
    branches: [ main, develop, criando-actions ]
  pull_request:
    branches: [ main, develop, criando-actions ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t frontend-image -f ./frontend/Dockerfile ./frontend

      - name: Run lint inside container
        run: docker run --rm frontend-image npm run lint
