name: Test Frontend

on:
  push:
    branches: [ main, develop, criando-actions ]
  pull_request:
    branches: [ main, develop, criando-actions ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for testing
        run: docker build -t frontend-test -f ./frontend/Dockerfile.test ./frontend

      - name: Run tests inside test container
        run: docker run --rm frontend-test
