name: Test Frontend

on:
  push:
    branches: [ main, develop, criando-actions ]
  pull_request:
    branches: [ main, develop, criando-actions ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (build stage only)
        run: docker build --target build -t frontend-test -f ./frontend/Dockerfile ./frontend

      - name: Run tests inside build container
        run: docker run --rm frontend-test npm run test -- --watchAll=false
